[project]
name = "mastereasybot"
version = "0.1.0"
description = "Telegram bot for scheduling"
authors = ["Woodgrouse16 <iryabov91@yandex.ru>"]
requires-python = ">=3.11"
dependencies = [
    "aiogram==2.25.2",
    "python-dotenv>=0.21.0",
]
